apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-145113-9uylh99hczki-service
spec:
  selector:
    app: enterprise-system-20260627-145113-9uylh99hczki
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
